### ISSUE TITLE
Abort a quick fix

### ISSUE THREAD

**Issue by PStellmann** [schematron-quickfix/sqf#10]
In the HTML Dialog sample the user can press the cancel button to abort the quick fix. Currently this is solved by passing the unmodified content (as far as possible, see issue #9). An even better solution would be if the xslt code could return something like sqf:abort/ which would abort the current quick fix.

This might be interesting for more complex xslt quick fixes as well when only during the execution it turns out that the quick fix is not applyable.

The user should be notified about the abort, though.

**Comment by nkutsche** [comment]
Hi Patrik,
why you don't use xsl:message with terminal="yes"? Message could be "Canceled by the user".
I think in the most cases the use-when attribute helps and for complex things xsl:message should be ok. Of course it should be supported by the implementation (I didn't tested it yet), but this is a different issue.

**Comment by PStellmann** [comment]
Good idea - much better than having a "magic element".
In oXygen it alreay works except that the message won't be displayed.

@octavianN: It would be nice if the messages from within a quick fix would be displayed just as any other message from XSLT transformation scenarios.

**Comment by octavianN** [comment]
Hi Patrik,
Thank you for the suggestion. I added an issue on out internal issue tracker to present the messages from the quick fix. But if you will use xsl:message with terminate="yes" you will get also a fatal error.

**Comment by PStellmann** [comment]
Actually I dislike the current behavior of oXygen on terminating xsl:messages in transformation scenarios as well. Especially since the actual message will be in the message window and the error window (which will be visible at first) does not contain the text. For this reason I prefer to have a catch on top level in my XSLT scripts that just catches the termination and provides an ordinary message:

`<xsl:catch errors="XTMM9000">
    <xsl:message>The transformation was aborted.</xsl:message>
</xsl:catch>`

So I think using a terminating message is the perfect way to abort a quick fix. Instead we could better think of a different behavior of oXygen in such a case in general!?

**Comment by octavianN** [comment]
Hi Patrik,
We present the message that we get from the processor. Yes, it will be better to present the message from the xsl:message element in this case. I added also your last comment on our issue.

We can consider this issue closed for SQF. The xsl:message with @terminate="yes" it solves the problem.
