### ISSUE TITLE
Replace on root element not working

### ISSUE THREAD

**Issue by PStellmann** [schematron-quickfix/sqf#11]
Applying this quick fix causes an error in oXygen:
`<sqf:fix id="test">
    <sqf:description>
        <sqf:title>replace root element</sqf:title>
    </sqf:description>
    <sqf:replace match="/*" select="."/>
</sqf:fix>`

error:
Cannot perform the quick fix: Cannot execute operation: Delete Node. Cause: ro.sync.xml.xpath.g: XPath failed due to: Finding root of tree: the context item is absent

**Comment by nkutsche** [comment]
I'm not sure, if we should discuss here implementation-(oxygen-)only issues.
Don't get me wrong, I'm really interested in this matter, but I think we should restrict us to topics, which are related to the language specification.
The oXygen mailing list would be a better platform for this.

**Comment by PStellmann** [comment]
Agreed. Moved it here: https://www.oxygenxml.com/forum/topic12977.html
