### ISSUE TITLE
Remove the sqf:keep element

### ISSUE THREAD

**Issue by nkutsche** [schematron-quickfix/sqf#14]
This issue was subject of a concept session during the XMLPrague 2016. Read the full concept paper [here](https://github.com/schematron-quickfix/sqf/blob/master/concept-papers/out/pdf/xmlprague-meeting.pdf).

**Issue Summary**
The first question was after a use case for the `sqf:keep` element:

The following example shows an Activity Element, which transforms all child elements of an specific namespace in the NULL namespace: 

```
<sqf:replace match=".//sqf:*" target="{local-name()}" node-type="element">
    <sqf:keep/>
</sqf:replace>
```

**Conclusions**
- The group agreed, that this is a reasonable use case of `sqf:keep` and it is impossible to do this with other SQF structures.
- But because this is a very special case, we proposed to remove the `sqf:keep` element from the specification.
- The use cases are also realizable by embedded XSLT.

**Comment by PStellmann** [comment]
The current discussion about maintaining the exact original content in #9 - which includes attributes  with defaults, xincludes and entities - could mean a comeback for the sqf:keep element. So we should wait before removing it.

**Comment by nkutsche** [comment]
I updated the spec and schema ([f1f8959](https://github.com/schematron-quickfix/sqf/commit/f1f895966e1834b8a9c6f5175505e8a93f1795b3)). The `sqf:keep` element was removed. The issue #9 will be solved by other solutions (`@unparsed-mode`, `@except` of `sqf:copy-of`).
