### ISSUE TITLE
The stringReplace operation should specify also the regexp flags 

### ISSUE THREAD

**Issue by octavianN** [schematron-quickfix/sqf#16]
Hello,

The sqf:stringReplace operation should specify also the "flags" for the regular expression. Flags that control multiline mode, case insensitivity, etc. I think we can add something similar with the flags attribute from the [xsl:analyze-string](https://www.w3.org/TR/xslt20/#element-analyze-string) element.

Now, as an workaround, you can use the sqf:replace operation and the xsl:analyze-string inside the operation. 

Best Regards,
Octavian

**Comment by nkutsche** [comment]
I updated the spec and schema with the following commits:
- [f1f8959](https://github.com/schematron-quickfix/sqf/commit/f1f895966e1834b8a9c6f5175505e8a93f1795b3)
- [0011042](https://github.com/schematron-quickfix/sqf/commit/0011042f91830f331ac1b00a26cea850ae00ffde)

The flag is now optional to the `sqf:stringReplace` element. The usage should be equal to the `xsl:analyze-string/@flags` attribute.
