### ISSUE TITLE
StringReplace for attributes

### ISSUE THREAD

**Issue by tofi86** [schematron-quickfix/sqf#18]
Either `sqf:stringReplace` does not work on attribute nodes but only on text nodes, or it isn't supported by oXygen (@octavianN).

```xml
<sch:rule context="@attribute">
  ....
  <sqf:stringReplace regex=" ">%20</sqf:stringReplace>
  ...
```

Any idea?

**Comment by octavianN** [comment]
The [`sqf:stringReplace`](http://schematron-quickfix.github.io/sqf/spec/SQFSpec.html#d0e1013) works only on text nodes. If you want to modify the value of an attribute you can use the `sqf:replace` operation and maybe use the `replace()` XPath function to change " " in "%20" .

**Comment by tofi86** [comment]
That's too bad...

Because `sqf:replace` resolves entities – even the XML default entities like `&amp;`. Which makes URLs with query parameters in attributes invalid when using `sqf:replace`. 😭

**Comment by octavianN** [comment]
A solution is to escape the '&'. Something like this:
```XML
<sqf:replace node-type="keep" target="attribute" select="replace(replace(., '&amp;', '&amp;amp;'), ' ', '%20')"/>
```

**Comment by tofi86** [comment]
That works, thanks! However, I just don't get it why oXygen would also resolve the default XML entities in quickfixes. But that's not an issue with SQF but with oXygen...

**Comment by octavianN** [comment]
Thank you, Tobias.
There is an issue on oXygen issue tracker related to this. I added you comment there.

**Comment by georgebina** [comment]
Resolving entities is correct, in my opinion, because you check the text value, not how that is encoded (XSLT and XPath do not have a notion of entities, neither schema languages), the issue seems to be in the serialization part and we will look into that.
Regards,
George

**Comment by tofi86** [comment]
Resolving entities is fine, but when replacing an attribute node or another element node, the XML default entities should be preserved.

Thanks for having a look, George and Octavian.
