### ISSUE TITLE
adding multiple attributes with sqf:add

### ISSUE THREAD

**Issue by PStellmann** [schematron-quickfix/sqf#19]
Hi,

I have a case where a quick fix needs to insert up to two attributes to multiple nodes. And it requires some processing to know, which attributes need to be added. So my code looks something like this:
```
<sqf:add match="//*[my:requiresFix(.)]" select="my:requiredAttributes(.)"/>
```

with the xslt:
```
<xsl:function name="my:requiredAttributes" as="attribute()*">
	<xsl:param name="element" as="element()"/>
	<!-- some processing... -->
	<xsl:attribute name="attribute1" select="'value1'"/>
	<xsl:attribute name="attribute2" select="'value2'"/>
</xsl:function>
```

I don't get any error message (from oXygen 18.1) but no attributes were added - probably because the default `@position` or sqf:add is "first-child" and I don't have child elements but attributes. But I can't specify "attribute" as `@position`!?

I already got a workaround but it is much less comfortable:
```
<sqf:add match="//*[my:needsAttribute1(.)]" node-type="attribute" target="attribute1" select="my:requiredAttributeValue1(.)"/>
<sqf:add match="//*[my:needsAttribute2(.)]" node-type="attribute" target="attribute2" select="my:requiredAttributeValue2(.)"/>
```

BTW: Handling it in XSLT using sqf:replace on the element is also no option because I don't want to have the attribute defaults being added...

Patrik

**Comment by octavianN** [comment]
Hi Patrik,

Thank you for the feedback. 
In oXygen we do not have support to insert multiple attributes on an element using one `sqf:add` operation. The only way to insert multiple attribute is to use multiple `sqf:add` operations with the node-type="attribute".

I think it should be possible insert multiple attributes using one `sqf:add` operation. I will add an issue on our issue tracker to improve this support.

Best Regards,
Octavian

**Comment by nkutsche** [comment]
This seems to be an oxygen-only issue. Anyway, I just added a JUnit test case for my Escali. It seems to work.
