### ISSUE TITLE
The call-fix strucure is not user friendly

### ISSUE THREAD

**Issue by nkutsche** [schematron-quickfix/sqf#2]
The call-fix structure, as it is defined in the current schema is not very user friendly and it is also not very powerful yet.
_Example:_

```
    <sqf:fix id="fix1">
        <sqf:description>
            <sqf:title>Calling fix</sqf:title>
        </sqf:description>
        <sqf:call-fix ref="fix2">
            <sqf:with-param name="param" select="value"/>
        </sqf:call-fix>
    </sqf:fix>
    <sqf:fix id="fix2">
        <sqf:param name="param" default="'defaultvalue'"/>
        <sqf:description>
            <sqf:title>Called fix <value-of select="$param"/></sqf:title>
        </sqf:description>
    </sqf:fix>
```

**These are the problems I see:**
1. fix1 and fix2 needs to contain a description. fix1 ignores the description of fix2. The description of fix2 will be used only if it is referenced by a Schematron assert directly. The description of fix2 will be every time “Called fix defaultvalue”.
2. In this example the parameter $param is not required. But if it is required, fix2 is not reference able directly from a Schematron assert. So the description will never be used.

I see two intensions to create modules in some way of QuickFixes:
1. The developer wants to reuse a package of activity elements.
   1a. A parameter for this package should be available inside of all XPath expressions of the activity elements (this is supported yet).
   1b. The call of these packages should be combinable with other additional activity elements (this is not supported yet).
2. The developer needs some fixes which are very similar. In this case the description is usually similar too.
   2a. The descriptions of the reused QuickFix should be able to reuse and parametrize.
   2b. Also the use-when condition should be able to reuse and parametrize.

_Any other problems or issues to call-fix?_

**My propose:**
I think we should split these module types into two different structures:
1. The current call-fix element should be used to call and parametrize a fix. It should reuse the description of the called fix, so the calling fix should not contain a description element any more. The parameter of a fix should be available inside of the use-when condition.
2. A new element (sqf:module, sqf:template, …?), which could contains at the beginning sqf:param elements and then only activity elements. According to it, a new “call-_“ element (sqf:call-module, sqf:call-templates) should call these modules. The call-_ element could contains also sqf:with-param elements and are available like the activity elements.

_Any other proposes to solve this issues?_

**Comment by octavianN** [comment]
I think that the current sqf:call-fix element it is ok, we don't need to change it. We just need to allow multiple sqf:call-fix elements between the sqf:fix operations (activity elements).
- For the first problem, where you want to customize the description of a fix using a call-fix. This can be solved by using a variable in the description of "fix1" . Something like:

```
    <sqf:fix id="fix1">
       <let name="var" select="values"/>
        <sqf:description>
            <sqf:title>Calling fix <value-of select="$var"/></sqf:title>
        </sqf:description>
         <sqf:call-fix ref="fix2">
            <sqf:with-param name="param" select="$var"/>
        </sqf:call-fix>
    </sqf:fix>

    <sqf:fix id="fix2">
        <sqf:param name="param" default="'defaultvalue'"/>
        <sqf:description>
            <sqf:title>Called fix</sqf:title>
        </sqf:description>
        <sqf:add><value-of select="$param"/></sqf:add>
    </sqf:fix>
```

In this case "fix2" is used only to refer some common operations that we defined in it. And the description of "fix1" is customized using the variable "var".
- For the second problem, to reuse a package of operations (activity elements). Yes, I think we should allow the sqf:call-fix element between the sqf:fix operations. 
  But I don't think we should create other element for this, the "sqf:fix" element already contains a package of operations. Yes, it contains also a description which is ignored when is referred with call-fix. But it is flexible, you can refer it also directly from an assert, and in this case the description is used.

**Comment by nkutsche** [comment]
I don't see, that the var variable help very much on my problems. For instance see the example I posted in issue #3:

```
<sqf:group id="add">
    <sqf:fix id="add1" use-when="$assertCount ge 1 and $assertCount le 3">
        <sqf:description>
            <sqf:title>Add a reference to the first of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[1]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
    <sqf:fix id="add2" use-when="$assertCount ge 2 and $assertCount le 3">
        <sqf:description>
            <sqf:title>Add a reference to the second of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[2]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
    <sqf:fix id="add3" use-when="$assertCount ge 3 and $assertCount le 3">
        <sqf:description>
            <sqf:title>Add a reference to the third of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[3]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
</sqf:group>
```

There are three fixes with almost the same code. If I create one generic fix and call it by call-fix as it is now possible, I get this:

```
<sqf:group id="add">
    <sqf:fix id="add1" use-when="$assertCount ge 1 and $assertCount le 3">
        <sqf:param name="pos" default="1"/>
        <sqf:description>
            <sqf:title>Add a reference to the first of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[$pos]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
    <sqf:fix id="add2" use-when="$assertCount ge 2 and $assertCount le 3">
        <sqf:description>
            <sqf:title>Add a reference to the second of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="2"/>
        </sqf:call-fix>
    </sqf:fix>
    <sqf:fix id="add3" use-when="$assertCount ge 3 and $assertCount le 3">
        <sqf:description>
            <sqf:title>Add a reference to the third of the assert/report elements.</sqf:title>
        </sqf:description>
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="3"/>
        </sqf:call-fix>
    </sqf:fix>
</sqf:group>
```

It is even one line more code! Ok, the complex part is just at one place, but I think it would be helpfull very much for the developers, if they could parametrize the description and the use-when condition like this:

```
<sqf:group id="add">
    <sqf:fix id="add1" use-when="$assertCount ge $pos and $assertCount le 3">
        <sqf:param name="pos" default="1"/>
        <sqf:description>
            <sqf:title>Add a reference to the assert/report elements on position <value-of select="$pos"/>.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[$pos]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
    <sqf:fix id="add2">
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="2"/>
        </sqf:call-fix>
    </sqf:fix>
    <sqf:fix id="add3">
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="3"/>
        </sqf:call-fix>
    </sqf:fix>
</sqf:group>
```

Less code, the description and the use-when condition just at one place too.

**Comment by octavianN** [comment]
The problem with this approach is that you cannot use the description from the called fix. This is because we discussed to allow multiple call-fix elements between the fix operations and you will not know which description to use. So, in your case you need descriptions also for "add2" and "add3" fixes.

Also the language will be more complicated by adding new elements (sqf:call-module and module). And I think the developers will not be happy about this. So I think it is code simplicity vs complexity of the language.

About the use-when condition, you can check also the condition from the called fix. The use-when condition doesn't need to be on the "add2" and "add3" fixes, can be set on the called fix.

**Comment by octavianN** [comment]
A solution to this issue can be the following one:
- make the quick fix description optional
- if a fix doesn't have a description, then:
  - will use the description from the call-fix element (if it has only one call-fix)
  - otherwise, the fix cannot be referred from assert/report (or if is referred will be presented as "Fix_with_no_title")
- if a fix has a description, then the fix description will be used

So, in this way you can parameterize a quick fix description:

```
<sqf:group id="add">
    <sqf:fix id="add1" use-when="$assertCount ge $pos and $assertCount le 3">
        <sqf:param name="pos" default="1"/>
        <sqf:description>
            <sqf:title>Add a reference to the assert/report elements on position <value-of select="$pos"/>.</sqf:title>
        </sqf:description>
        <sqf:add match="$asserts[$pos]" target="sqf:fix" node-type="attribute" select="
            string-join((@sqf:fix,
            $id), ' ')"/>
    </sqf:fix>
    <sqf:fix id="add2">
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="2"/>
        </sqf:call-fix>
    </sqf:fix>
    <sqf:fix id="add3">
        <sqf:call-fix ref="add1">
            <sqf:with-param name="pos" select="3"/>
        </sqf:call-fix>
    </sqf:fix>
</sqf:group>
```

But also, you don't need to add a description for a call fix if is not used from an assert/report:

```
 <sqf:fix id="addTitleAndDescription">
     <sqf:description>
         <sqf:title>Add the title and description elements.</sqf:title>
     </sqf:description>
     <sqf:call-fix ref="addTitle"/>
     <sqf:call-fix ref="addDescription"/>
 </sqf:fix>
 <sqf:fix id="addTitle">
     <sqf:add target="title" node-type="element"/>
     <sqf:add target="subtitle" node-type="element"/>
 </sqf:fix>
 <sqf:fix id="addDescription">
     <sqf:add target="abstract" node-type="element"/>
     <sqf:add target="author" node-type="element"/>
 </sqf:fix>

```

**Comment by nkutsche** [comment]
Yes, this would be one solution, I was thinking about it too. But I think that this more complicate as an strict and clean split using two different structures. A feature of this solution is, that the developer is able to use the description of the called fix or to override it by an custom description.
Maybe we should wait for more input/opinions/ideas of SQF users?

**Comment by Arithmeticus** [comment]
As a now-avid user of SQF's, I really want to have available multiple nestable sqf:call-fixes. That [only one is currently allowed](https://www.oxygenxml.com/forum/topic12880.html) seems to defeat the purpose. I would want to have something like the second solution in place, and to encourage SQF editors to think about them, and construct them, as if they were nestable xsl:functions or xsl:templates. 

For me, sqf:description is mere icing, the equivalent of the verbose name of a function, variable, or template, so I don't have a strong opinion on how nested sqf:descriptions get handled. Perhaps sqf:call-fix or sqf:description or sqf:title could have an attribute added, to allow designers to specify how, e.g., 

```
<sqf:fix id="addTitleAndDescription">
    <sqf:description>
        <sqf:title sqf:import-fixes="true"/>
    </sqf:description>
    <sqf:call-fix ref="addTitle"/>
    <sqf:call-fix ref="addDescription"/>
</sqf:fix>
<sqf:fix id="addTitle">
    <sqf:description>
        <sqf:title>Add the title elements.</sqf:title>
    </sqf:description>
    <sqf:add target="title" node-type="element"/>
    <sqf:add target="subtitle" node-type="element"/>
</sqf:fix>
<sqf:fix id="addDescription">
    <sqf:description>
        <sqf:title>Add the description elements.</sqf:title>
    </sqf:description>
    <sqf:add target="abstract" node-type="element"/>
    <sqf:add target="author" node-type="element"/>
</sqf:fix>
```

**Comment by nkutsche** [comment]
This issue was subject of a concept session during the XMLPrague 2016. Read the full concept paper [here](https://github.com/schematron-quickfix/sqf/blob/master/concept-papers/out/pdf/xmlprague-meeting.pdf). Following, a conclusion summary and open issues:
- `sqf:description` is optional and unbounded, but the language (`@xml:lang`) needs to be unique in one `sqf:fix` element 
  (if possible, auto completion should add it automatically when creating `sqf:fix` elements)
- The `sqf:fix` must have a description, if there is no or more than one `sqf:call-fix` with a description inside.
- If you have exactly one `sqf:call-fix` and no `sqf:description` element, the called fix must have a `sqf:description` or inherit one.
- The languages of the descriptions of the called fix and the calling fix could be different:
- Use case: Use `sqf:call-fix` to add a different language to an existing fix.

Open issues
1. This concept ignores some issues of the [localisation proposal](https://github.com/schematron-quickfix/sqf/issues/1).
2. XSD has limitations, so the [schematron-quickfix.xsd](https://github.com/schematron-quickfix/sqf/blob/master/schemas/schematron-quickFix.xsd) would be very lax. The order of the `sqf:fix` content would be checked by Schematron ([sqf.sch](https://github.com/schematron-quickfix/sqf/blob/master/schemas/sqf.sch)). One suggestion was, to switch the basic schema ([schematron-quickfix.xsd](https://github.com/schematron-quickfix/sqf/blob/master/schemas/schematron-quickFix.xsd)) to RELAX NG

**Comment by nkutsche** [comment]
The updated specification of the last commit ([f1f8959](https://github.com/schematron-quickfix/sqf/commit/f1f895966e1834b8a9c6f5175505e8a93f1795b3)) specifies now the new content model of the `sqf:fix` element (allow zero or more descriptions, multiple sqf:call-fix elements, etc.). I created a new issue #17 for the maintenance of a new RELAX NG schema version.

So I think, this issue should be now closed.
