### ISSUE TITLE
Replace a word in an element

### ISSUE THREAD

**Issue by fergcondon** [schematron-quickfix/sqf#22]
Hi there,

I am looking into Schematron Quick Fixes for the first time, so apologies if my question is a little basic :) 

I would like to create a sqf to replace a word in a sentence. For example, replace the word "orientate" with "orient".  What does the schema look like for this type of rule?

Thanks in advance.
Fergal

**Comment by stefan-jung** [comment]
Hey @fergcondon, try something like this, see [DOCTALES DITA termchecker presentation](https://doctales.github.io/presentations/presentation-dita-ot-day/index.html#/8/1):

```xml
<sch:pattern id="truck-d35e134">
  <sch:rule context="text()">
    <sch:report test="contains(/*/@xml:lang, 'en-GB') and contains(., 'truck')"
                role="warning"
                sqf:fix="sqfGroupTruckd35e134">The term 'truck' is not allowed.</sch:report>
    <sqf:group id="sqfGroupTruckd35e134">
      <sqf:fix id="termTruckd35e1284">
        <sqf:description>
          <sqf:title>Replace with an allowed term: 'lorry'</sqf:title>
          <sqf:p>A truck is a motor vehicle designed to transport cargo.</sqf:p>
        </sqf:description>
        <sqf:stringReplace regex="truck">lorry</sqf:stringReplace>
      </sqf:fix>
    </sqf:group>
  </sch:rule>
</sch:pattern>
```

**Comment by fergcondon** [comment]
Hey @xephon2 

Thanks so much for the tip, and quick response. Works perfectly!

**Comment by stefan-jung** [comment]
@fergcondon, you're welcome. Please close the issue.
