### ISSUE TITLE
duplicate attribute name sqf

### ISSUE THREAD

**Issue by fergcondon** [schematron-quickfix/sqf#23]
Hi,

We have the following metadata in our ditamaps.

        <othermeta name="docnumber" content="H-12345"/>
        <othermeta name="doctype" content="Installation Guide"/>
        <othermeta name="docrev" content="01"/>
        <othermeta name="business" content="Controls EMEA"/>

Is it possible to create a sqf rule to point to only one of these lines? For example,  restrict the content on the doctype line to just Installation Guide or Manual?

Many thanks in advance,

**Comment by nkutsche** [comment]
Hi,

it's low on info to understand what you want to do, so I have to guess.

You can use the `match` attribute on `sqf:replace`, `sqf:delete` or `sqf:add`.
E.g. if you have the following Schematron rule:

```
<sch:rule context="*[othermeta]">
   <sch:report test="othermeta[@name != 'doctype']" sqf:fix="fix-it">Found bad othermeta</sch:assert>
   <sqf:fix id="fix-it">
      <sqf:description>
         <sqf:title>Remove bad othermeta</sqf:title>
      </sqf:description>
      <sqf:delete match="othermeta[@name != 'doctype']"/>
   </sqf:fix>
</sch:rule>
```

As I wrote, this is just a guess about your needs. If you need something different, please provide more informations.

**Comment by fergcondon** [comment]
Hi @nkutsche 

Thanks so much for the response. I will try my best to explain :) 

I want to set a rule for only the "doctype" line. So if someone writes something other than "Installation Guide" in the content attribute, I want an error to appear. Here is what I have so far;

  
     <sch:pattern id="RestrictDoctype1">
        <sch:rule context="othermeta">
            <sch:assert test="matches (@content, 'Installation Guide')"
                role="error"
                sqf:fix="sqfdoctypefix">Invalid doctype name</sch:assert>
                <sqf:fix id="sqfdoctypefix">
                    <sqf:description>
                        <sqf:title>Invalid doctype name</sqf:title>
                    </sqf:description>
                    <sqf:replace match="othermeta[@content != '']"/>
                </sqf:fix>
        </sch:rule>
    </sch:pattern>

The problem is this is pointing to all 4 of the othermeta elements. I only want it to point to one. I'm not sure if this is possible.

Thanks again.

**Comment by PStellmann** [comment]
I think your problem is not about sqf but about schematron.

A schematron rule that checks the doctype could look like this:
```
<sch:pattern id="RestrictDoctype1">
    <sch:rule context="othermeta[@name = 'doctype']">
        <sch:assert test="@content = 'Installation Guide'" role="error">
            The doctype should be 'Installation Guide'
        </sch:assert>
    </sch:rule>
</sch:pattern>
```
Of course additionally you could a a quick fix to set the content the the reqired value...

**Comment by fergcondon** [comment]
Hi @PStellmann 

This is great, thanks so much. This is what I was looking for;

<sch:rule context="othermeta[@name = 'doctype']"> 

This now highlights only one othermeta element instead of all 4.
