### ISSUE TITLE
New activityElement: "goto"

### ISSUE THREAD

**Issue by PStellmann** [schematron-quickfix/sqf#4]
I'm using schematron quite often to check a document for consistency. Thus, there might be more (usually two) different nodes involved. In such a case there will be an individual error reported for each node and each could be solved by modifying the node itself or the other.
Providing the appropriate QuickFixes is no problem. But there are cases when the author can't easily decide which one should be modified (or the fix is too complex to be done automatically). Now I'd like to provide an additional QuickFix that simply moves the caret to the other related node.

It might as well be a nice addition to a usual QuickFix to move the caret to the modified node (or the first/last/... of the modified nodes).

The syntax could be something like this:

```
<sqf:goto match="(preceding::* | following::*)[@refAttribute = current()/@refAttribute]" pos="start"/>
```

The pos-attribute would allow these values (analog to Oxygens XsltOperation): before, start (inside), end (inside), after.

**Comment by georgebina** [comment]
Hi Patrick,

If you think in the context of an authoring environment that makes sense, but otherwise, if you run this outside an authoring environment (like running escali directly) then a goto action does not really make sense.
As a workaround, you may try to see if an empty insert before that element solves the problem.

Best Regards,
George

**Comment by PStellmann** [comment]
I agree that this makes only sense in an authoring environment. But using sqf in an authoring environment makes **_a lot**_ sense! So I think it is still reasonable for sqf providing this option.

However, sqf:add without any content doesn't work - probably because the caret is not moved explicitly but the new content is just block marked - and without content there is no block mark.
Using sqf:replace to replace the element by itself doesn't work either because it the new content isn't block marked. (I think this is a small inconsistency within oxygen.)

**Comment by nkutsche** [comment]
Hi, I don't see this in SQF because you don't want to fix something. I think it could be a very useful extension for the see-attribute of Schematron. Something like this:

&lt;assert test="..." see="xpath:{../sibling[$pos]}">

**Comment by PStellmann** [comment]
Yes, I agree that such information is more related to the schematron message than to a fix.
After your suggestion for using the see-attribute I see no more content?
However, it would be nice to allow multiple xpath expressions - including those to other documents - as links. Maybe even some kind of link-element within the text. But this is probably not the right place to discus enhancements to schematron - although I'm not aware of any suitable (and active) place for this...

**Comment by nkutsche** [comment]
Oh, I wrote it from my smartphone, there was no preview option.
My suggestion was, somthing like:

```
<sch:assert test="..." see="xpath:{(preceding::* | following::*)[@refAttribute = current()/@refAttribute]}">
```

But you are right, this is not the right place to discuss Schematron extensions. Maybe we should set up a new one...

**Comment by nkutsche** [comment]
This should be closed, because we decided, that this is not the correct platform.

**Comment by PStellmann** [comment]
Just as a final note: The probably best solution would be to support html within schematron messages. This way it is possible to add a link to the corresponding section that might need to be modified. This feature is planned for oXygen.
